In [1]:
import pandas as pd 


In [2]:
df=pd.read_csv("gk_qna_dataset.csv")
df.head(5)

,question,answer
0,"What is the capital of ""France""?",Paris
1,"What is the capital of ""Germany""?",Berlin
2,"What is the capital of ""Italy""?",Rome
3,"What is the capital of ""Spain""?",Madrid
4,"What is the capital of ""Japan""?",Tokyo


In [3]:
df['question'][0]

'What is the capital of "France"?'

tokenization

In [5]:
import re 

def tokenize(text):
       #lowercase 
       text=text.lower()


       # remove quotes 
       text=re.sub(r"[\'\"]", "", text)


       # remove all punctuations 
       text=re.sub(r"[^a-z0-9\s]", "", text)
       text=re.sub(r"\s+", " ", text)

       #remove extra space
       tokens=text.split()


       return tokens 

In [6]:
print(tokenize(df['question'][0]))

['what', 'is', 'the', 'capital', 'of', 'france']


In [7]:
vocab={'UNK': 0}

In [8]:
def build_vocab(row):
       print(row['question'],row['answer'])

       tokenized_question = tokenize(row['question'])
       tokenized_answer = tokenize(row['answer'])
       print(tokenized_question,tokenized_answer)
       merged_tokens=tokenized_question+tokenized_answer
       for token in merged_tokens:
              if token not in vocab:
                     vocab[token]=len(vocab)

In [9]:
df.apply(build_vocab,axis=1)

What is the capital of "France"? Paris
['what', 'is', 'the', 'capital', 'of', 'france'] ['paris']
What is the capital of "Germany"? Berlin
['what', 'is', 'the', 'capital', 'of', 'germany'] ['berlin']
What is the capital of "Italy"? Rome
['what', 'is', 'the', 'capital', 'of', 'italy'] ['rome']
What is the capital of "Spain"? Madrid
['what', 'is', 'the', 'capital', 'of', 'spain'] ['madrid']
What is the capital of "Japan"? Tokyo
['what', 'is', 'the', 'capital', 'of', 'japan'] ['tokyo']
What is the capital of "Canada"? Ottawa
['what', 'is', 'the', 'capital', 'of', 'canada'] ['ottawa']
What is the capital of "Brazil"? Brasilia
['what', 'is', 'the', 'capital', 'of', 'brazil'] ['brasilia']
What is the capital of "Australia"? Canberra
['what', 'is', 'the', 'capital', 'of', 'australia'] ['canberra']
What is the capital of "India"? New Delhi
['what', 'is', 'the', 'capital', 'of', 'india'] ['new', 'delhi']
What is the capital of "China"? Beijing
['what', 'is', 'the', 'capital', 'of', 'china'] ['b

0      None
1      None
2      None
3      None
4      None
       ... 
166    None
167    None
168    None
169    None
170    None
Length: 171, dtype: object

In [26]:
vocab

{'UNK': 0,
 'what': 1,
 'is': 2,
 'the': 3,
 'capital': 4,
 'of': 5,
 'france': 6,
 'paris': 7,
 'germany': 8,
 'berlin': 9,
 'italy': 10,
 'rome': 11,
 'spain': 12,
 'madrid': 13,
 'japan': 14,
 'tokyo': 15,
 'canada': 16,
 'ottawa': 17,
 'brazil': 18,
 'brasilia': 19,
 'australia': 20,
 'canberra': 21,
 'india': 22,
 'new': 23,
 'delhi': 24,
 'china': 25,
 'beijing': 26,
 'russia': 27,
 'moscow': 28,
 'united': 29,
 'states': 30,
 'washington': 31,
 'dc': 32,
 'mexico': 33,
 'city': 34,
 'egypt': 35,
 'cairo': 36,
 'turkey': 37,
 'ankara': 38,
 'argentina': 39,
 'buenos': 40,
 'aires': 41,
 'south': 42,
 'korea': 43,
 'seoul': 44,
 'indonesia': 45,
 'jakarta': 46,
 'pakistan': 47,
 'islamabad': 48,
 'bangladesh': 49,
 'dhaka': 50,
 'nepal': 51,
 'kathmandu': 52,
 'sri': 53,
 'lanka': 54,
 'colombo': 55,
 'thailand': 56,
 'bangkok': 57,
 'malaysia': 58,
 'kuala': 59,
 'lumpur': 60,
 'vietnam': 61,
 'hanoi': 62,
 'uae': 63,
 'abu': 64,
 'dhabi': 65,
 'iran': 66,
 'tehran': 67,
 'iraq':

In [10]:
len(vocab)

243

text to indices 

In [11]:
def text_to_indices(text, word_to_idx=None):
       if word_to_idx is None:
              word_to_idx = vocab

       tokens = tokenize(text) if isinstance(text, str) else text

       indexed_text=[]
       for token in tokens:
              indexed_text.append(word_to_idx.get(token, word_to_idx['UNK']))
       return indexed_text

In [12]:
text_to_indices("what is the capital of Vanuatu".split())

[1, 2, 3, 4, 5, 0]

Dataset and Dataloader 

In [32]:
! pip install torch

Defaulting to user installation because normal site-packages is not writeable
  Using cached torch-2.11.0-cp313-cp313-win_amd64.whl.metadata (29 kB)
  Using cached setuptools-81.0.0-py3-none-any.whl.metadata (6.6 kB)
  Using cached sympy-1.14.0-py3-none-any.whl.metadata (12 kB)
  Using cached mpmath-1.3.0-py3-none-any.whl.metadata (8.6 kB)
Using cached torch-2.11.0-cp313-cp313-win_amd64.whl (114.6 MB)
Using cached setuptools-81.0.0-py3-none-any.whl (1.1 MB)
Using cached sympy-1.14.0-py3-none-any.whl (6.3 MB)
Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)

   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   ---------------------------------------- 0/4 [mpmath]
   -------------------------------


[notice] A new release of pip is available: 26.0.1 -> 26.1.1
[notice] To update, run: C:\Users\Shuvo\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [13]:
import torch
from torch.utils.data import Dataset, DataLoader

In [14]:
df

,question,answer
0,"What is the capital of ""France""?",Paris
1,"What is the capital of ""Germany""?",Berlin
2,"What is the capital of ""Italy""?",Rome
3,"What is the capital of ""Spain""?",Madrid
4,"What is the capital of ""Japan""?",Tokyo
...,...,...
166,"Can you tell me, ""Which bird cannot fly""?",Ostrich
167,"I was wondering, ""What is 'H2O' commonly called""?",Water
168,"I was wondering, ""Which planet is known as the...",Mars
169,"Can you tell me, ""What is the main religion in...",Islam


In [62]:
df.shape[0]

171

In [63]:
index=0 
df.iloc[index]['question']

'What is the capital of "France"?'

In [64]:
index=0 
text_to_indices(tokenize(df.iloc[index]['question']))

[1, 2, 3, 4, 5, 6]

In [65]:
answer_to_idx = {answer: idx for idx, answer in enumerate(df['answer'].astype(str).str.strip().unique())}
idx_to_answer = {idx: answer for answer, idx in answer_to_idx.items()}

class QADataset(Dataset):
       def __init__(self,df,vocab,answer_to_idx):
              self.df = df
              self.vocab = vocab
              self.answer_to_idx = answer_to_idx
       def __len__(self):
              return len(self.df)
       def __getitem__(self,index):
              row = self.df.iloc[index]
              question = text_to_indices(tokenize(row['question']))
              answer = self.answer_to_idx[str(row['answer']).strip()]
              return torch.tensor(question, dtype=torch.long), torch.tensor(answer, dtype=torch.long)

In [67]:
dataset=QADataset(df,vocab,answer_to_idx)


In [68]:
dataset[1]

(tensor([1, 2, 3, 4, 5, 8]), tensor(1))

In [69]:
dataloader=DataLoader(dataset,batch_size=1,shuffle=True)

In [70]:
for question,answer in dataloader:
       print(question,answer)

tensor([[240, 232, 241, 242,  93, 215, 216, 218]]) tensor([67])
tensor([[230, 231,  79,  84,   3, 161, 162]]) tensor([51])
tensor([[237,   1, 238, 239,   1, 131, 145, 133, 121]]) tensor([47])
tensor([[234, 235, 236,  93, 179,   2, 101, 102,   3, 180,   5, 181, 182]]) tensor([56])
tensor([[ 93, 197,   2, 198, 103]]) tensor([61])
tensor([[ 93, 183,   2, 101, 121, 195]]) tensor([60])
tensor([[230, 231,  93,  94,  95,  96,  97]]) tensor([35])
tensor([[237,   1, 238, 239,  79, 105,   3, 106, 107]]) tensor([37])
tensor([[ 1,  2,  3,  4,  5, 29, 30]]) tensor([11])
tensor([[240, 232, 241, 242,  79,  84,   3, 161, 162]]) tensor([51])
tensor([[240, 232, 241, 242,   1,   2,  89,  90,  91]]) tensor([34])
tensor([[ 95, 232, 233,   1,   2, 124, 120, 121]]) tensor([41])
tensor([[  1,   2,   3, 220, 223, 224,  70,  71]]) tensor([70])
tensor([[234, 235, 236,  79,  84,   3, 165]]) tensor([52])
tensor([[79, 80, 81]]) tensor([32])
tensor([[ 1,  2,  3,  4,  5, 14]]) tensor([4])
tensor([[237,   1, 238, 239,

sequeze 

In [71]:
import torch 
x=torch.tensor([[1,2,4]])
print(x.shape)

torch.Size([1, 3])


In [72]:
y=x.squeeze()
print(y.shape)

torch.Size([3])


RNN architecture 

In [73]:
import torch.nn as nn 
class simpleRNN(nn.Module):
       def __init__(self,vocab_size,answer_size,embedding_dim=50,hidden_size=64):
              super().__init__()
              self.embedding = nn.Embedding(vocab_size,embedding_dim)
              self.rnn = nn.RNN(embedding_dim,hidden_size,batch_first=True)
              self.fc=nn.Linear(hidden_size,answer_size)
       def forward(self,question):
              embedded=self.embedding(question)
              _,final=self.rnn(embedded)
              return self.fc(final.squeeze(0))
                               


In [74]:
model=simpleRNN(vocab_size=len(vocab),answer_size=len(answer_to_idx))

In [75]:
criterion=nn.CrossEntropyLoss()
optimizer=torch.optim.Adam(model.parameters(),lr=0.001)
epochs=50 

In [76]:
for epoch in range(epochs):
       total_loss = 0
       for question,answer in  dataloader:
              optimizer.zero_grad()
              output=model(question)
              loss=criterion(output,answer)
              loss.backward()
              optimizer.step()
              total_loss+=loss.item()
       if (epoch+1) % 10 == 0:
              print(f"Epoch {epoch+1}/{epochs}, Loss: {total_loss/len(dataloader):.4f}")     
       
       

Epoch 10/50, Loss: 0.2055
Epoch 20/50, Loss: 0.0242
Epoch 30/50, Loss: 0.0073
Epoch 40/50, Loss: 0.0027
Epoch 50/50, Loss: 0.0011


In [77]:
vocab.items()

dict_items([('UNK', 0), ('what', 1), ('is', 2), ('the', 3), ('capital', 4), ('of', 5), ('france', 6), ('paris', 7), ('germany', 8), ('berlin', 9), ('italy', 10), ('rome', 11), ('spain', 12), ('madrid', 13), ('japan', 14), ('tokyo', 15), ('canada', 16), ('ottawa', 17), ('brazil', 18), ('brasilia', 19), ('australia', 20), ('canberra', 21), ('india', 22), ('new', 23), ('delhi', 24), ('china', 25), ('beijing', 26), ('russia', 27), ('moscow', 28), ('united', 29), ('states', 30), ('washington', 31), ('dc', 32), ('mexico', 33), ('city', 34), ('egypt', 35), ('cairo', 36), ('turkey', 37), ('ankara', 38), ('argentina', 39), ('buenos', 40), ('aires', 41), ('south', 42), ('korea', 43), ('seoul', 44), ('indonesia', 45), ('jakarta', 46), ('pakistan', 47), ('islamabad', 48), ('bangladesh', 49), ('dhaka', 50), ('nepal', 51), ('kathmandu', 52), ('sri', 53), ('lanka', 54), ('colombo', 55), ('thailand', 56), ('bangkok', 57), ('malaysia', 58), ('kuala', 59), ('lumpur', 60), ('vietnam', 61), ('hanoi', 62),

In [79]:
idx_to_word={idx: word for word, idx in vocab.items()}
idx_to_word

{0: 'UNK',
 1: 'what',
 2: 'is',
 3: 'the',
 4: 'capital',
 5: 'of',
 6: 'france',
 7: 'paris',
 8: 'germany',
 9: 'berlin',
 10: 'italy',
 11: 'rome',
 12: 'spain',
 13: 'madrid',
 14: 'japan',
 15: 'tokyo',
 16: 'canada',
 17: 'ottawa',
 18: 'brazil',
 19: 'brasilia',
 20: 'australia',
 21: 'canberra',
 22: 'india',
 23: 'new',
 24: 'delhi',
 25: 'china',
 26: 'beijing',
 27: 'russia',
 28: 'moscow',
 29: 'united',
 30: 'states',
 31: 'washington',
 32: 'dc',
 33: 'mexico',
 34: 'city',
 35: 'egypt',
 36: 'cairo',
 37: 'turkey',
 38: 'ankara',
 39: 'argentina',
 40: 'buenos',
 41: 'aires',
 42: 'south',
 43: 'korea',
 44: 'seoul',
 45: 'indonesia',
 46: 'jakarta',
 47: 'pakistan',
 48: 'islamabad',
 49: 'bangladesh',
 50: 'dhaka',
 51: 'nepal',
 52: 'kathmandu',
 53: 'sri',
 54: 'lanka',
 55: 'colombo',
 56: 'thailand',
 57: 'bangkok',
 58: 'malaysia',
 59: 'kuala',
 60: 'lumpur',
 61: 'vietnam',
 62: 'hanoi',
 63: 'uae',
 64: 'abu',
 65: 'dhabi',
 66: 'iran',
 67: 'tehran',
 68: 'ir

In [83]:
def predict(question_text,vocab,model,idx_to_answer):
       model.eval()
       with torch.no_grad():
              indices=text_to_indices(question_text, vocab)
              if not indices:
                     return "<UNK>"
              x=torch.tensor(indices, dtype=torch.long).unsqueeze(0)
              pred=torch.argmax(model(x),dim=1).item()
              return idx_to_answer.get(pred,"<UNK>")

In [84]:
tests=[
       "What is the capital of France?",
       "Who is the president of the United States?",
       "What is the largest mammal?",]
for test in tests:
       answer=predict(test,vocab,model,idx_to_word)
       print(f"Q: {test}\nA: {answer}\n")

Q: What is the capital of France?
A: UNK

Q: Who is the president of the United States?
A: rome

Q: What is the largest mammal?
A: ankara

